/vis/open OGL
#/vis/open VRML2FILE
#/vis/open DAWNFILE

/action/file/OverWrite y
/action/file/RunName test
/action/file/SaveDirectory output_tree

# Load geometry
/control/execute geometry/5deg_1.2T.mac
# /control/execute geometry/geom_deuteron.mac

# Z-X view
/vis/viewer/set/upVector 1 0 0
/vis/viewer/set/viewpointThetaPhi 90. 90.

# X-Y view
# /vis/viewer/set/viewpointThetaPhi 0. 90.

/vis/drawVolume

# 添加坐标轴
/vis/scene/add/axes 0 0 0 6000 mm

/vis/scene/endOfEventAction accumulate
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1

# 设置颜色
/vis/modeling/trajectories/drawByCharge-0/set 1 red    # 质子 - 红色
/vis/modeling/trajectories/drawByCharge-0/set 0 blue   # 中子 - 蓝色
/vis/modeling/trajectories/drawByCharge-0/set -1 green # 负电荷 - 绿色

# 启用轨迹存储用于可视化
/tracking/storeTrajectory 1

# 加载几何
/control/execute /home/tbt/workspace/dpol/smsimulator5.5/d_work/geometry/5deg_1.2T.mac

# 输出文件名设置
/action/file/SaveDirectory output_tree/
/action/file/RunName d+Sn124E190g050ynp_np_sametime_vis

# 粒子输入类型为 Tree（用于多粒子同时入射）
/action/gun/Type Tree
/action/gun/tree/InputFileName /home/tbt/workspace/dpol/smsimulator5.5/d_work/rootfiles/d+Sn124E190g050ynp/dbreakb09.root
/action/gun/tree/TreeName tree



# 运行事件并进入交互模式
/action/gun/tree/beamOn 9

# 查看保存的事件
/vis/reviewKeptEvents

# 进入交互模式，保持GUI窗口打开
# 注意：需要从终端直接运行程序而不使用宏来进入交互模式