# /vis/open OGL  # Restore original OGL setting
# /vis/open VRML2FILE
#/vis/open DAWNFILE
# /vis/open OGLSWin
# /vis/open OGLIXWin
/vis/open OGLIQt
# get environment variable SMSIMDIR
/control/getEnv SMSIMDIR

/action/file/OverWrite y
/action/file/RunName TEST
/action/file/SaveDirectory {SMSIMDIR}/data/simulation/g4output

# Load geometry
# /control/execute {SMSIMDIR}/configs/simulation/geometry/5deg_1.2T.mac
/control/execute {SMSIMDIR}/configs/simulation/geometry/3deg_1.15T.mac
# /control/execute geometry/geom_deuteron.mac

# Z-X view
/vis/viewer/set/upVector 1 0 0
/vis/viewer/set/viewpointThetaPhi 90. 90.
# /vis/viewer/set/rotationStyle freeRotation
# X-Y view
# /vis/viewer/set/viewpointThetaPhi 0. 90.

/vis/drawVolume

# 添加坐标轴
/vis/scene/add/axes 0 0 0 6000 mm

/vis/scene/endOfEventAction accumulate
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1


# /action/gun/Type Gaus
# /action/gun/AngleX 0 deg
# /action/gun/AngleY 0 deg
# /action/gun/PositionXSigma 1 cm
# /action/gun/PositionYSigma 1 cm
# /action/gun/SetBeamParticleName proton
# /action/gun/Energy 190 MeV

# /action/gun/Type Pencil
# /action/gun/Position 0 0 0 m
# /action/gun/SetBeamParticleName proton
# /action/gun/Energy 190 MeV
# /run/beamOn 1

# /action/gun/Type Tree
# # /action/gun/tree/InputFileName {SMSIMDIR}/d_work/rootfiles/d+Sn124E190g050ynp/dbreakb09.root
# /action/gun/tree/InputFileName {SMSIMDIR}/data/simulation/g4input/ypol_slect_rotate_back/ypol_np_Pb208_g050.root
# # /action/gun/tree/InputFileName {SMSIMDIR}/d_work/roo   tfiles/d+Pb208E190g050xyz/dbreakb01.root

# /action/gun/tree/TreeName tree
# /action/gun/tree/beamOn 23
# /vis/viewer/flush
# /event/verbose 1
# /tracking/verbose 1

# /control/alias runf "/action/gun/tree/beamOn 1; /vis/viewer/flush "
# 上个命令失败了

# 设置氘核束流  
# /action/gun/Type Pencil  
# /action/gun/SetBeamParticleName deuteron  
# /action/gun/Energy 380 MeV  
# /run/beamOn 10      
# /tracking/storeTrajectory 1

# /action/gun/Type Tree
# # /action/gun/tree/InputFileName /home/tian/workspace/dpol/smsimulator5.5/data/simulation/g4input/z_pol/b_discrete/d+Sn112E190g060zpn/dbreakb07.root
# /action/gun/tree/InputFileName {SMSIMDIR}/data/simulation/g4input/y_pol/phi_random/d+Pb208E190g060ynp/dbreak.root
# /action/gun/tree/TreeName tree
# /action/gun/tree/beamOn 1000


/action/gun/Type Pencil
/action/gun/SetBeamParticleName neutron
/action/gun/Energy 190 MeV
/run/beamOn 10


# 运行事件  
# /run/beamOn 10
/vis/viewer/flush
