# =========================================================================
# =========================================================================
#
# Geometry for the SAMURAI Dayone experiment
#
/control/getEnv SMSIMDIR
# field map file
/samurai/geometry/Dipole/Angle 30 deg
/samurai/geometry/Dipole/FieldFile /nas/data/Bryan/field_map/180626-1,20T-3000.bin
/samurai/geometry/Dipole/FieldFactor 1

# Target
/samurai/geometry/Target/SetTarget false
/samurai/geometry/Target/Material Sn
/samurai/geometry/Target/Size 80 80 30 mm
/samurai/geometry/Target/Position 0 0 0 mm
/samurai/geometry/Target/Angle 10 deg

#-----------------------------------
# PDCs
# Z should be distance from MAGcenter to PDC Z=0 plane
/samurai/geometry/PDC/Angle 45 deg
/samurai/geometry/PDC/Position1 30 0 400 cm
/samurai/geometry/PDC/Position2 30 0 500 cm

#-----------------------------------
# Dump
# Z should be distance from MAGcenter to the beam dump Z=0 plane
/samurai/geometry/Dump/SetDump false
/samurai/geometry/Dump/Angle 39 deg
/samurai/geometry/Dump/Position 0 -250 10000 mm

#-----------------------------------
# NEBULA
/samurai/geometry/NEBULA/ParameterFileName geometry/NEBULA_Dayone.csv
/samurai/geometry/NEBULA/DetectorParameterFileName geometry/NEBULA_Detectors_Dayone.csv
#

#-----------------------------------
# UPDATE (should be called after changing geometry)
/samurai/geometry/FillAir true
/samurai/geometry/Update

# Automatically determine detector positions
/samurai/geometry/AutoConfig geometry/10deg_1.2T.mac