# =========================================================================
# =========================================================================
#
# Geometry for the SAMURAI Dayone experiment
#
#-----------------------------------
# field map file
/samurai/geometry/Dipole/Angle 30 deg
/samurai/geometry/Dipole/FieldFile field_map/180703-1,30T-3000.bin
/samurai/geometry/Dipole/FieldFactor 1

# Target
/samurai/geometry/Target/SetTarget false
/samurai/geometry/Target/Material CsI
/samurai/geometry/Target/Size 80 80 3 mm
/samurai/geometry/Target/Position -65 0 -617 mm
/samurai/geometry/Target/Angle 10 deg

#-----------------------------------
# PDCs
# Z should be distance from MAGcenter to PDC Z=0 plane
/samurai/geometry/PDC/Angle 57 deg
/samurai/geometry/PDC/Position1 300 0 4500 mm
/samurai/geometry/PDC/Position2 300 0 5500 mm

#-----------------------------------
# Dump
# Z should be distance from MAGcenter to the beam dump Z=0 plane
/samurai/geometry/Dump/Angle 39.3 deg
/samurai/geometry/Dump/Position 0 -250 10000 mm

#-----------------------------------
# NEBULA
/samurai/geometry/NEBULA/ParameterFileName geometry/NEBULA_Dayone.csv
/samurai/geometry/NEBULA/DetectorParameterFileName geometry/NEBULA_Detectors_Dayone.csv
#

#-----------------------------------
# UPDATE (should be called after changing geometry)
/samurai/geometry/FillAir true
/samurai/geometry/Update

/samurai/geometry/AutoConfig geometry/auto.mac