{
    // Automatically generated by setup_conda.sh
    cout << "\n=== Loading SMSIM libraries (Conda Env) ===" << endl;
    
    // 获取环境变量中的路径
    const char* smsim_dir = gSystem->Getenv("SMSIMDIR");
    if (!smsim_dir) {
        cout << "Error: SMSIMDIR environment variable not set!" << endl;
    } else {
        TString libPath = TString::Format("%s/build/lib", smsim_dir);
        // 添加库查找路径
        gSystem->AddDynamicPath(libPath);
        cout << "Library path added: " << libPath << endl;
    }

    TString libs[] = {
        "libsmdata.so",       
        "libsmlogger.so",
        "libsmaction.so",
        "libsmconstruction.so",
        "libsmphysics.so",
        "libsim_deuteron_core.so"
    };
    
    for (Int_t i = 0; i < 6; i++) {
        TString lib = libs[i];
        if (gSystem->Load(lib) >= 0) {
            cout << "  [OK] " << lib << endl;
        } else {
            cout << "  [XX] Failed to load: " << lib << endl;
        }
    }
    
    cout << "--- Loading Analysis Tools ---" << endl;
    if (gSystem->Load("libpdcanalysis.so") >= 0) {
        cout << "  [OK] libpdcanalysis.so" << endl;
    } else if (gSystem->Load("libanalysis.so") >= 0) {
        cout << "  [OK] libanalysis.so" << endl;
    } else {
        cout << "  [!!] Warning: Analysis library not found" << endl;
    }
    cout << "===========================================\n" << endl;
}
