#!/bin/bash

# ==============================================================================
# 1. 基础环境检查与清理
# ==============================================================================

# [重要] 检查是否在 Conda 环境中
if [[ -z "$CONDA_PREFIX" ]]; then
    echo "警告: 你似乎没有激活 Conda 环境 (anaroot-env)。"
    echo "请先运行: micromamba activate anaroot-env"
    # 如果你希望强制退出，取消下面这行的注释
    # return 1 2>/dev/null || exit 1
fi

# [修改] 移除旧的 ROOT 和 Geant4 source
# Conda 环境激活后，'root' 和 'geant4-config' 命令应该直接可用。
# 不要再 source /home/tbt/software/root/... 
# 不要再 source /home/common/.../geant4make.sh

# ==============================================================================
# 2. 项目路径定义
# ==============================================================================

# 定义当前项目的根目录
# 如果你在这个脚本所在的目录下 source 它，建议使用 pwd 动态获取，方便移植
# export SMSIMDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# 或者保持你原本的硬编码路径：
export SMSIMDIR=/home/tbt/workspace/Dpol_smsimulator

# [TODO] 确认 TARTSYS (ANAROOT 安装路径)
# 如果你是用 install_anaroot.sh 安装到了 conda 环境里，这里应该是 $CONDA_PREFIX
# 如果你是安装在本地某个文件夹，请指向那个文件夹
# export TARTSYS=/home/kokubun/smsim_for_spana/anaroot/install
export TARTSYS=/home/tbt/software/anaroot/install
# 如果 ANAROOT 安装在 Conda 环境系统目录下，解开下面这行：
# export TARTSYS=$CONDA_PREFIX

echo "Setting up environment for: $SMSIMDIR"
echo "ANAROOT System (TARTSYS): $TARTSYS"

# ==============================================================================
# 3. 导出项目特定的环境变量 (保持不变)
# ==============================================================================

export PATH=$PATH:$SMSIMDIR/bin

# Geant4 Simulation Libraries
export G4SMLIBDIR=$SMSIMDIR/libs/smg4lib
export G4SMPHYSICSDIR=$SMSIMDIR/libs/smg4lib/src/physics
export G4SMACTIONDIR=$SMSIMDIR/libs/smg4lib/src/action
export G4SMCONSTRUCTIONDIR=$SMSIMDIR/libs/smg4lib/src/construction
export G4SMDATADIR=$SMSIMDIR/libs/smg4lib/src/data

# 编译参数
export G4SMCPPFLAGS="-I$G4SMLIBDIR/include"
# 注意：Conda 里的 Geant4 通常是版本 11+，不再使用 old style linker list，
# 但如果是你自己的库，保持这样没问题。
export G4SMLDLIBS="-lsmphysics -lsmaction -lsmconstruction -lsmdata"

# ==============================================================================
# 4. 设置 Library Path (链接库路径)
# ==============================================================================

# [修改] 使用简洁的追加方式
# Conda 的库路径 ($CONDA_PREFIX/lib) 已经默认在系统查找范围内，不需要加到 LD_LIBRARY_PATH
# 只需要加你自己的项目库和 ANAROOT 库
ADDITIONAL_LIB_PATHS="$SMSIMDIR/build/lib:$TARTSYS/lib"

if [[ -z "$LD_LIBRARY_PATH" ]]; then
    export LD_LIBRARY_PATH="$ADDITIONAL_LIB_PATHS"
else
    # 避免重复添加
    if [[ ":$LD_LIBRARY_PATH:" != *":$SMSIMDIR/build/lib:"* ]]; then
        export LD_LIBRARY_PATH="$ADDITIONAL_LIB_PATHS:$LD_LIBRARY_PATH"
    fi
fi

# LIBRARY_PATH (用于编译期间)
if [[ -z "$LIBRARY_PATH" ]]; then
    export LIBRARY_PATH="$SMSIMDIR/build/lib"
else
    export LIBRARY_PATH="$SMSIMDIR/build/lib:$LIBRARY_PATH"
fi

# ==============================================================================
# 5. 设置 ROOT Include Path (防止编译字典报错)
# ==============================================================================

ADDITIONAL_INCLUDES="$SMSIMDIR/libs/smg4lib/src/data/include:$SMSIMDIR/libs/analysis/include:$TARTSYS/include"

if [[ -z "$ROOT_INCLUDE_PATH" ]]; then
    export ROOT_INCLUDE_PATH="$ADDITIONAL_INCLUDES"
else
    export ROOT_INCLUDE_PATH="$ROOT_INCLUDE_PATH:$ADDITIONAL_INCLUDES"
fi

# ==============================================================================
# 6. 生成 rootlogon.C (自动加载库)
# ==============================================================================

export ROOT_PRELOAD_LIBS="libsmlogger.so:libsmdata.so:libsmaction.so:libsmconstruction.so:libsmphysics.so:libsim_deuteron_core.so:libanalysis.so"

# 确保目录存在
mkdir -p $SMSIMDIR/build/lib

# 动态生成 rootlogon.C
cat > $SMSIMDIR/rootlogon.C << EOF
{
    // Automatically generated by setup_conda.sh
    cout << "\n=== Loading SMSIM libraries (Conda Env) ===" << endl;
    
    // 获取环境变量中的路径
    const char* smsim_dir = gSystem->Getenv("SMSIMDIR");
    if (!smsim_dir) {
        cout << "Error: SMSIMDIR environment variable not set!" << endl;
    } else {
        TString libPath = TString::Format("%s/build/lib", smsim_dir);
        // 添加库查找路径
        gSystem->AddDynamicPath(libPath);
        cout << "Library path added: " << libPath << endl;
    }

    TString libs[] = {
        "libsmdata.so",       
        "libsmlogger.so",
        "libsmaction.so",
        "libsmconstruction.so",
        "libsmphysics.so",
        "libsim_deuteron_core.so"
    };
    
    for (Int_t i = 0; i < 6; i++) {
        TString lib = libs[i];
        if (gSystem->Load(lib) >= 0) {
            cout << "  [OK] " << lib << endl;
        } else {
            cout << "  [XX] Failed to load: " << lib << endl;
        }
    }
    
    cout << "--- Loading Analysis Tools ---" << endl;
    if (gSystem->Load("libpdcanalysis.so") >= 0) {
        cout << "  [OK] libpdcanalysis.so" << endl;
    } else if (gSystem->Load("libanalysis.so") >= 0) {
        cout << "  [OK] libanalysis.so" << endl;
    } else {
        cout << "  [!!] Warning: Analysis library not found" << endl;
    }
    cout << "===========================================\n" << endl;
}
EOF

echo "Environment setup complete."
echo "Use 'root -l' inside $SMSIMDIR to start with loaded libraries."