# 生成图像文件的可视化配置

# 使用VRML输出而不是OpenGL
/vis/open VRML2FILE

# 输出文件设置
/action/file/OverWrite y
/action/file/RunName d+Pb208E190g050xyz_np_sametime_image
/action/file/SaveDirectory output_tree/

# 加载几何体
/control/execute geometry/5deg_1.2T.mac

# 设置视角
/vis/viewer/set/upVector 1 0 0
/vis/viewer/set/viewpointThetaPhi 90. 90.

# 绘制几何体
/vis/drawVolume

# 设置轨迹显示
/vis/scene/endOfEventAction accumulate
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/set 1 red
/vis/modeling/trajectories/drawByCharge-0/set 0 blue
/vis/modeling/trajectories/drawByCharge-0/set -1 green

# 启用轨迹存储
/tracking/storeTrajectory 1

# 设置输入源
/action/gun/Type Tree
/action/gun/tree/InputFileName /home/tbt/workspace/dpol/smsimulator5.5/d_work/rootfiles/d+Pb208E190g050xyz/dbreakb01.root
/action/gun/tree/TreeName tree

# 运行事件
/run/beamOn 3
