
name := smphysics

CPPFLAGS += $(shell $(ROOTSYS)/bin/root-config --cflags) -g
# CPPFLAGS += $(shell $(ROOTSYS)/bin/root-config --cflags) -g -DDEBUG
LDLIBS += $(shell $(ROOTSYS)/bin/root-config --libs)

include ../GNUmakefile.in