# include 层级  
# 使用 OGLS 存储模式以提高性能
# OGLS: OpenGL存储模式，旋转更流畅
# OGL: 默认OpenGL模式
# /vis/open OGLS 1280x720  
/vis/open OGLIQt
# /vis/open DAWN
# /vis/open OGL
# /vis/open OGLSQt
# /vis/viewer/set/projection orthogonal
# get environment variable SMSIMDIR
# /vis/open OGLSQt
/control/getEnv SMSIMDIR
# /event/keepCurrentEvent true

/action/file/OverWrite y
/action/file/RunName DTest
/action/file/SaveDirectory /home/tian/workspace/dpol/smsimulator5.5/data/simulation/g4output

# Load geometry with absolute path
# /control/execute /home/tian/workspace/dpol/smsimulator5.5/configs/simulation/DbeamTest/nopdc/B080T.mac   # 0.8T
# /control/execute /home/tian/workspace/dpol/smsimulator5.5/configs/simulation/DbeamTest/nopdc/B100T.mac   # 1.0T
# /control/execute /home/tian/workspace/dpol/smsimulator5.5/configs/simulation/DbeamTest/nopdc/B120T.mac   # 1.2T
# /control/execute /home/tian/workspace/dpol/smsimulator5.5/configs/simulation/DbeamTest/nopdc/B140T.mac   # 1.4T
# /control/execute /home/tian/workspace/dpol/smsimulator5.5/configs/simulation/DbeamTest/nopdc/B160T.mac   # 1.6T
# /control/execute /home/tian/workspace/dpol/smsimulator5.5/configs/simulation/DbeamTest/nopdc/B180T.mac   # 1.8T
# /control/execute /home/tian/workspace/dpol/smsimulator5.5/configs/simulation/DbeamTest/nopdc/B200T.mac   # 2.0T
# /control/execute {SMSIMDIR}/configs/simulation/geometry/3deg_1.15T.mac

/control/execute {SMSIMDIR}/configs/simulation/DbeamTest/detailMag1to1.2T/run_deuteron_B115T.mac

/vis/viewer/set/autoRefresh false
/vis/verbose errors

# 设置 Z-X 视图 (俯视/侧视)
/vis/viewer/set/upVector 1 0 0
/vis/viewer/set/viewpointThetaPhi 90. 90.
/vis/drawVolume
/vis/scene/add/axes 0 0 0 6000 mm

# 轨迹无限累积
/vis/scene/endOfEventAction accumulate
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
/vis/scene/endOfRunAction accumulate
# ==========================================

# # ==========================================
# /action/gun/Type Pencil
# /action/gun/SetBeamParticleName deuteron
# /action/gun/Position 0 0 -4000 mm

# # 设置能量
# /action/gun/Energy 380 MeV

# /run/beamOn 1
# /samurai/geometry/Target/Positiom 0 0 -4 m
# 切换到高斯束  
# # 创建一个针对轨迹级别的过滤器
# /vis/filtering/trajectories/create/attributeFilter primaryFilter

# # 设置过滤属性为 "Parent ID" (初级粒子的 Parent ID 为 0)
# /vis/filtering/trajectories/primaryFilter/setAttribute ParentID
# /vis/filtering/trajectories/primaryFilter/addValue 0
/vis/filtering/trajectories/create/particleFilter particleTypeFilter
/vis/filtering/trajectories/particleTypeFilter/add deuteron

# 这样即便有初级中子或光子（如果存在的话），也不会显示

/action/gun/Type Gaus  
# 设置粒子种类  
/action/gun/SetBeamParticleName deuteron  
# /action/gun/Position 0 0 -4000 mm
# 设置中心能量  
/action/gun/Energy 380 MeV  
# 设置位置高斯宽度（可选）  
/action/gun/PositionXSigma 1 mm  
/action/gun/PositionYSigma 1 mm  
# 设置角度高斯宽度（可选）  
/action/gun/AngleXSigma 0.1 mrad  
/action/gun/AngleYSigma 0.1 mrad  
# 发射事件  
/run/beamOn 100
# # ==========================================# /action/gun/Type Pencil
# /action/gun/SetBeamParticleName deuteron

# # 【关键诊断步骤】把位置向上挪 mm# /action/gun/Position 1 1 -4 m
# /action/gun/AngleY 0.14 rad
# # 设置新能量
# /action/gun/Energy 190 MeV
# /run/beamOn 5
# # ==========================================
# # 4. 最后：一次性把两条线画出来
# # ==========================================
# # 开启自动刷新
/vis/viewer/set/autoRefresh true


# /vis/reviewKeptEvents
