# include 层级  
/vis/open OGL  

# get environment variable SMSIMDIR
/control/getEnv SMSIMDIR

/action/file/OverWrite y
/action/file/RunName DTest
/action/file/SaveDirectory /home/tian/workspace/dpol/smsimulator5.5/data/simulation/g4output

# Load geometry with absolute path
# /control/execute /home/tian/workspace/dpol/smsimulator5.5/configs/simulation/DbeamTest/nopdc/B080T.mac   # 0.8T
# /control/execute /home/tian/workspace/dpol/smsimulator5.5/configs/simulation/DbeamTest/nopdc/B100T.mac   # 1.0T
# /control/execute /home/tian/workspace/dpol/smsimulator5.5/configs/simulation/DbeamTest/nopdc/B120T.mac   # 1.2T
/control/execute /home/tian/workspace/dpol/smsimulator5.5/configs/simulation/DbeamTest/nopdc/B140T.mac   # 1.4T
  
# Z-X view  
/vis/viewer/set/upVector 1 0 0
/vis/viewer/set/viewpointThetaPhi 90. 90.
# /vis/viewer/set/rotationStyle freeRotation  
  
/vis/drawVolume  
  
# 添加坐标轴  
/vis/scene/add/axes 0 0 0 6000 mm  
  
# 轨迹显示设置  
/vis/scene/endOfEventAction accumulate  
/vis/scene/add/trajectories smooth  
/vis/modeling/trajectories/create/drawByCharge  
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true  
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1  
  
# 设置氘核束流  
/action/gun/Type Pencil  
/action/gun/SetBeamParticleName deuteron  
/action/gun/Energy 380 MeV  
/action/gun/Position 0 0 -4 m  
  
/tracking/storeTrajectory 1  
  
# 运行事件  
/run/beamOn 10
/vis/viewer/flush